### ISSUE TITLE
Error: foundry.js:68326 You are attempting to upload a file with a disallowed file extension.

### ISSUE THREAD

**Issue by buttonpushertv** [SvenWerlen/moulinette-obsidian#1]
On Windows 11, Chrome Version 122.0.6261.129 (Official Build) (64-bit), FVTT V11.315(node.js), and 5e V3.0.4, and only the Moulinette modules active when exporting Scenes and Actors, I get this error quite often, but there is no info in the error to give me a sense of what files it is trying to "upload" (or I guess, save).

Any thoughts on what may be causing it?

**Comment by SvenWerlen** [comment]
Hi there,
Do you see any other error (in red) in the console. Knowing the filename might give me some indication about the issue. Also, do you end up with missing files in the export!
Btw, thank you for using this very new module :-)

**Comment by huxoll** [comment]
I have the same issue, and I believe in my case it's a .webp.  I have an animated portrait for one actor, and that is the missing one.
![Screenshot 2024-03-22 at 9 14 45 AM](https://github.com/SvenWerlen/moulinette-obsidian/assets/132249/d50360f9-3b5e-4efc-ac70-3297a13f7d15)
<img width="809" alt="ExportLog" src="https://github.com/SvenWerlen/moulinette-obsidian/assets/132249/0291340f-7951-4365-9c0e-019887d8bd4b">

**Comment by buttonpushertv** [comment]
Thanks for creating the module. It's a cool idea. I do have things missing, but there are so many errors that I can't trace to a specific file, so I don't know exactly what or how many files are missing (out of the total that should be there - again something that would be good to learn from what the plugin expects to export).

The trouble is that it shows the error occuring with no other errors around it. As you can see here at the end of an Actor's-only export pass on a world with multiple actors.

![image](https://github.com/SvenWerlen/moulinette-obsidian/assets/24526709/c852beb2-fd64-4492-be20-16ac44c10e0d)

The DNDBeyond error I can understand due the CORS policy, but all of those trailing "disallowed file extension" errors don't show me what file they are attempting to "upload". 

Could it be related to the error message just below the DNDBeyond error? The one that failed to fetch at something called "MoulinetteObsidian.uploadBinary"? Could that be a setting on my server that disallows files types on my node.js instance? 

I expanded the final 'disallowed' error in case there is something in there that is helpful for tracking down the issue.

**Comment by SvenWerlen** [comment]
Thx @huxoll. I think I know what the error could be. It looks like Moulinette is trying to keep the parameters `?...` and FVTT will then complain about it (as disallowed file extension)

**Comment by SvenWerlen** [comment]
Version `v-11.1.1` should fix both issues @huxoll & @buttonpushertv

**Comment by SvenWerlen** [comment]
Note : the module won't download any URL (starting with http) anymore. This might be an issue for non-local installation.

**Comment by huxoll** [comment]
I've confirmed there's no longer an error doing the export.
